/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.group8.view.editRestaurant;

import com.group8.controller.RestaurantEditController;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class RestaurantSchedule extends javax.swing.JPanel {

    
    RestaurantEditController controller;
    /**
     * Creates new form RestaurantSchedule
     */
    public RestaurantSchedule(RestaurantEditController controller) {
        this.controller = controller;
        initComponents();
    }
    
    public RestaurantSchedule() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scheduleLabel = new javax.swing.JLabel();
        headerLabels = new javax.swing.JPanel();
        dayHeader = new javax.swing.JLabel();
        startHeader = new javax.swing.JLabel();
        startHeader1 = new javax.swing.JLabel();
        closedHeader = new javax.swing.JLabel();
        openHeader = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        day1 = new javax.swing.JPanel();
        dayLabel1 = new javax.swing.JLabel();
        startField1 = new javax.swing.JTextField();
        stopField1 = new javax.swing.JTextField();
        closedBox1 = new javax.swing.JCheckBox();
        nonStopBox1 = new javax.swing.JCheckBox();
        day2 = new javax.swing.JPanel();
        dayLabel2 = new javax.swing.JLabel();
        startField2 = new javax.swing.JTextField();
        stopField2 = new javax.swing.JTextField();
        closedBox2 = new javax.swing.JCheckBox();
        nonStopBox2 = new javax.swing.JCheckBox();
        day3 = new javax.swing.JPanel();
        dayLabel3 = new javax.swing.JLabel();
        startField3 = new javax.swing.JTextField();
        stopField3 = new javax.swing.JTextField();
        closedBox3 = new javax.swing.JCheckBox();
        nonStopBox3 = new javax.swing.JCheckBox();
        day4 = new javax.swing.JPanel();
        dayLabel4 = new javax.swing.JLabel();
        startField4 = new javax.swing.JTextField();
        stopField4 = new javax.swing.JTextField();
        closedBox4 = new javax.swing.JCheckBox();
        nonStopBox4 = new javax.swing.JCheckBox();
        day5 = new javax.swing.JPanel();
        dayLabel5 = new javax.swing.JLabel();
        startField5 = new javax.swing.JTextField();
        stopField5 = new javax.swing.JTextField();
        closedBox5 = new javax.swing.JCheckBox();
        nonStopBox5 = new javax.swing.JCheckBox();
        day6 = new javax.swing.JPanel();
        dayLabel6 = new javax.swing.JLabel();
        startField6 = new javax.swing.JTextField();
        stopField6 = new javax.swing.JTextField();
        closedBox6 = new javax.swing.JCheckBox();
        nonStopBox6 = new javax.swing.JCheckBox();
        day7 = new javax.swing.JPanel();
        dayLabel7 = new javax.swing.JLabel();
        startField7 = new javax.swing.JTextField();
        stopField7 = new javax.swing.JTextField();
        closedBox7 = new javax.swing.JCheckBox();
        nonStopBox7 = new javax.swing.JCheckBox();

        setPreferredSize(new java.awt.Dimension(310, 20));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scheduleLabel.setText("Schedule:");
        add(scheduleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        headerLabels.setOpaque(false);
        headerLabels.setPreferredSize(new java.awt.Dimension(310, 20));
        headerLabels.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dayHeader.setText("Day:");
        dayHeader.setPreferredSize(new java.awt.Dimension(70, 20));
        headerLabels.add(dayHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, -1, -1));

        startHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        startHeader.setText("Starts:");
        startHeader.setPreferredSize(new java.awt.Dimension(50, 20));
        headerLabels.add(startHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, -1));

        startHeader1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        startHeader1.setText("Ends:");
        startHeader1.setPreferredSize(new java.awt.Dimension(50, 20));
        headerLabels.add(startHeader1, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 0, -1, -1));

        closedHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closedHeader.setText("Closed");
        closedHeader.setPreferredSize(new java.awt.Dimension(50, 20));
        headerLabels.add(closedHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, -1, -1));

        openHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        openHeader.setText("24/7");
        openHeader.setPreferredSize(new java.awt.Dimension(50, 20));
        headerLabels.add(openHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 0, -1, -1));

        add(headerLabels, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 22, -1, -1));

        content.setName("scheduleContent"); // NOI18N
        content.setOpaque(false);
        content.setPreferredSize(new java.awt.Dimension(310, 250));
        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        day1.setName("TheDay1"); // NOI18N
        day1.setOpaque(false);
        day1.setPreferredSize(new java.awt.Dimension(310, 20));
        day1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dayLabel1.setText("Monday");
        dayLabel1.setPreferredSize(new java.awt.Dimension(70, 20));
        day1.add(dayLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, -1, -1));

        startField1.setText("12:00");
        startField1.setName(""); // NOI18N
        startField1.setPreferredSize(new java.awt.Dimension(60, 20));
        startField1.setSize(new java.awt.Dimension(50, 20));
        day1.add(startField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 0, -1, 20));

        stopField1.setText("20:00");
        stopField1.setPreferredSize(new java.awt.Dimension(60, 20));
        stopField1.setSize(new java.awt.Dimension(50, 20));
        day1.add(stopField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, 20));

        closedBox1.setPreferredSize(new java.awt.Dimension(28, 20));
        day1.add(closedBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 0, -1, -1));

        nonStopBox1.setPreferredSize(new java.awt.Dimension(28, 20));
        day1.add(nonStopBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 0, -1, -1));

        content.add(day1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, -1, -1));

        day2.setOpaque(false);
        day2.setPreferredSize(new java.awt.Dimension(310, 20));
        day2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dayLabel2.setText("Tuesday");
        dayLabel2.setPreferredSize(new java.awt.Dimension(70, 20));
        day2.add(dayLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, -1, -1));

        startField2.setText("12:00");
        startField2.setName(""); // NOI18N
        startField2.setPreferredSize(new java.awt.Dimension(60, 20));
        startField2.setSize(new java.awt.Dimension(50, 20));
        startField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startField2ActionPerformed(evt);
            }
        });
        day2.add(startField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 0, -1, 20));

        stopField2.setText("20:00");
        stopField2.setPreferredSize(new java.awt.Dimension(60, 20));
        stopField2.setSize(new java.awt.Dimension(50, 20));
        day2.add(stopField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, 20));

        closedBox2.setPreferredSize(new java.awt.Dimension(28, 20));
        day2.add(closedBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 0, -1, -1));

        nonStopBox2.setPreferredSize(new java.awt.Dimension(28, 20));
        day2.add(nonStopBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 0, -1, -1));

        content.add(day2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        day3.setOpaque(false);
        day3.setPreferredSize(new java.awt.Dimension(310, 20));
        day3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dayLabel3.setText("Wednesday");
        dayLabel3.setPreferredSize(new java.awt.Dimension(70, 20));
        day3.add(dayLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, -1, -1));

        startField3.setText("12:00");
        startField3.setName(""); // NOI18N
        startField3.setPreferredSize(new java.awt.Dimension(60, 20));
        startField3.setSize(new java.awt.Dimension(50, 20));
        day3.add(startField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 0, -1, 20));

        stopField3.setText("20:00");
        stopField3.setPreferredSize(new java.awt.Dimension(60, 20));
        stopField3.setSize(new java.awt.Dimension(50, 20));
        day3.add(stopField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, 20));

        closedBox3.setPreferredSize(new java.awt.Dimension(28, 20));
        day3.add(closedBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 0, -1, -1));

        nonStopBox3.setPreferredSize(new java.awt.Dimension(28, 20));
        day3.add(nonStopBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 0, -1, -1));

        content.add(day3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 74, -1, -1));

        day4.setOpaque(false);
        day4.setPreferredSize(new java.awt.Dimension(310, 20));
        day4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dayLabel4.setText("Thursday");
        dayLabel4.setPreferredSize(new java.awt.Dimension(70, 20));
        day4.add(dayLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, -1, -1));

        startField4.setText("12:00");
        startField4.setName(""); // NOI18N
        startField4.setPreferredSize(new java.awt.Dimension(60, 20));
        startField4.setSize(new java.awt.Dimension(50, 20));
        day4.add(startField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 0, -1, 20));

        stopField4.setText("20:00");
        stopField4.setPreferredSize(new java.awt.Dimension(60, 20));
        stopField4.setSize(new java.awt.Dimension(50, 20));
        day4.add(stopField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, 20));

        closedBox4.setPreferredSize(new java.awt.Dimension(28, 20));
        day4.add(closedBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 0, -1, -1));

        nonStopBox4.setPreferredSize(new java.awt.Dimension(28, 20));
        day4.add(nonStopBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 0, -1, -1));

        content.add(day4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 108, -1, -1));

        day5.setOpaque(false);
        day5.setPreferredSize(new java.awt.Dimension(310, 20));
        day5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dayLabel5.setText("Friday");
        dayLabel5.setPreferredSize(new java.awt.Dimension(70, 20));
        day5.add(dayLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, -1, -1));

        startField5.setText("12:00");
        startField5.setName(""); // NOI18N
        startField5.setPreferredSize(new java.awt.Dimension(60, 20));
        startField5.setSize(new java.awt.Dimension(50, 20));
        day5.add(startField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 0, -1, 20));

        stopField5.setText("20:00");
        stopField5.setPreferredSize(new java.awt.Dimension(60, 20));
        stopField5.setSize(new java.awt.Dimension(50, 20));
        day5.add(stopField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, 20));

        closedBox5.setPreferredSize(new java.awt.Dimension(28, 20));
        day5.add(closedBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 0, -1, -1));

        nonStopBox5.setPreferredSize(new java.awt.Dimension(28, 20));
        day5.add(nonStopBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 0, -1, -1));

        content.add(day5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 142, -1, -1));

        day6.setOpaque(false);
        day6.setPreferredSize(new java.awt.Dimension(310, 20));
        day6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dayLabel6.setText("Saturday");
        dayLabel6.setPreferredSize(new java.awt.Dimension(70, 20));
        day6.add(dayLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, -1, -1));

        startField6.setText("12:00");
        startField6.setName(""); // NOI18N
        startField6.setPreferredSize(new java.awt.Dimension(60, 20));
        startField6.setSize(new java.awt.Dimension(50, 20));
        day6.add(startField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 0, -1, 20));

        stopField6.setText("20:00");
        stopField6.setPreferredSize(new java.awt.Dimension(60, 20));
        stopField6.setSize(new java.awt.Dimension(50, 20));
        day6.add(stopField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, 20));

        closedBox6.setPreferredSize(new java.awt.Dimension(28, 20));
        day6.add(closedBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 0, -1, -1));

        nonStopBox6.setPreferredSize(new java.awt.Dimension(28, 20));
        day6.add(nonStopBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 0, -1, -1));

        content.add(day6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 176, -1, -1));

        day7.setOpaque(false);
        day7.setPreferredSize(new java.awt.Dimension(310, 20));
        day7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dayLabel7.setText("Sunday");
        dayLabel7.setPreferredSize(new java.awt.Dimension(70, 20));
        day7.add(dayLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, -1, -1));

        startField7.setText("12:00");
        startField7.setName(""); // NOI18N
        startField7.setPreferredSize(new java.awt.Dimension(60, 20));
        startField7.setSize(new java.awt.Dimension(50, 20));
        day7.add(startField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 0, -1, 20));

        stopField7.setText("20:00");
        stopField7.setPreferredSize(new java.awt.Dimension(60, 20));
        stopField7.setSize(new java.awt.Dimension(50, 20));
        day7.add(stopField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, 20));

        closedBox7.setPreferredSize(new java.awt.Dimension(28, 20));
        day7.add(closedBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 0, -1, -1));

        nonStopBox7.setPreferredSize(new java.awt.Dimension(28, 20));
        day7.add(nonStopBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 0, -1, -1));

        content.add(day7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 44, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void startField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startField2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox closedBox1;
    private javax.swing.JCheckBox closedBox2;
    private javax.swing.JCheckBox closedBox3;
    private javax.swing.JCheckBox closedBox4;
    private javax.swing.JCheckBox closedBox5;
    private javax.swing.JCheckBox closedBox6;
    private javax.swing.JCheckBox closedBox7;
    private javax.swing.JLabel closedHeader;
    private javax.swing.JPanel content;
    private javax.swing.JPanel day1;
    private javax.swing.JPanel day2;
    private javax.swing.JPanel day3;
    private javax.swing.JPanel day4;
    private javax.swing.JPanel day5;
    private javax.swing.JPanel day6;
    private javax.swing.JPanel day7;
    private javax.swing.JLabel dayHeader;
    private javax.swing.JLabel dayLabel1;
    private javax.swing.JLabel dayLabel2;
    private javax.swing.JLabel dayLabel3;
    private javax.swing.JLabel dayLabel4;
    private javax.swing.JLabel dayLabel5;
    private javax.swing.JLabel dayLabel6;
    private javax.swing.JLabel dayLabel7;
    private javax.swing.JPanel headerLabels;
    private javax.swing.JCheckBox nonStopBox1;
    private javax.swing.JCheckBox nonStopBox2;
    private javax.swing.JCheckBox nonStopBox3;
    private javax.swing.JCheckBox nonStopBox4;
    private javax.swing.JCheckBox nonStopBox5;
    private javax.swing.JCheckBox nonStopBox6;
    private javax.swing.JCheckBox nonStopBox7;
    private javax.swing.JLabel openHeader;
    private javax.swing.JLabel scheduleLabel;
    private javax.swing.JTextField startField1;
    private javax.swing.JTextField startField2;
    private javax.swing.JTextField startField3;
    private javax.swing.JTextField startField4;
    private javax.swing.JTextField startField5;
    private javax.swing.JTextField startField6;
    private javax.swing.JTextField startField7;
    private javax.swing.JLabel startHeader;
    private javax.swing.JLabel startHeader1;
    private javax.swing.JTextField stopField1;
    private javax.swing.JTextField stopField2;
    private javax.swing.JTextField stopField3;
    private javax.swing.JTextField stopField4;
    private javax.swing.JTextField stopField5;
    private javax.swing.JTextField stopField6;
    private javax.swing.JTextField stopField7;
    // End of variables declaration//GEN-END:variables
}
