/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.group8.view.editRestaurant;

import com.group8.controller.RestaurantEditController;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author john
 */
public class RestaurantSchedule extends javax.swing.JPanel {

    
    RestaurantEditController controller;
    /**
     * Creates new form RestaurantSchedule
     */
    public RestaurantSchedule(RestaurantEditController controller) {
        this.controller = controller;
        initComponents();
    }
    
    public RestaurantSchedule() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scheduleLabel = new javax.swing.JLabel();
        headerLabels = new javax.swing.JPanel();
        dayHeader = new javax.swing.JLabel();
        startHeader = new javax.swing.JLabel();
        startHeader1 = new javax.swing.JLabel();
        closedHeader = new javax.swing.JLabel();
        openHeader = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        day1 = new javax.swing.JPanel();
        dayLabel1 = new javax.swing.JLabel();
        startField1 = new javax.swing.JTextField();
        stopField1 = new javax.swing.JTextField();
        closedBox1 = new javax.swing.JCheckBox();
        nonStopBox1 = new javax.swing.JCheckBox();
        day2 = new javax.swing.JPanel();
        dayLabel2 = new javax.swing.JLabel();
        startField2 = new javax.swing.JTextField();
        stopField2 = new javax.swing.JTextField();
        closedBox2 = new javax.swing.JCheckBox();
        nonStopBox2 = new javax.swing.JCheckBox();
        day3 = new javax.swing.JPanel();
        dayLabel3 = new javax.swing.JLabel();
        startField3 = new javax.swing.JTextField();
        stopField3 = new javax.swing.JTextField();
        closedBox3 = new javax.swing.JCheckBox();
        nonStopBox3 = new javax.swing.JCheckBox();
        day4 = new javax.swing.JPanel();
        dayLabel4 = new javax.swing.JLabel();
        startField4 = new javax.swing.JTextField();
        stopField4 = new javax.swing.JTextField();
        closedBox4 = new javax.swing.JCheckBox();
        nonStopBox4 = new javax.swing.JCheckBox();
        day5 = new javax.swing.JPanel();
        dayLabel5 = new javax.swing.JLabel();
        startField5 = new javax.swing.JTextField();
        stopField5 = new javax.swing.JTextField();
        closedBox5 = new javax.swing.JCheckBox();
        nonStopBox5 = new javax.swing.JCheckBox();
        day6 = new javax.swing.JPanel();
        dayLabel6 = new javax.swing.JLabel();
        startField6 = new javax.swing.JTextField();
        stopField6 = new javax.swing.JTextField();
        closedBox6 = new javax.swing.JCheckBox();
        nonStopBox6 = new javax.swing.JCheckBox();
        day7 = new javax.swing.JPanel();
        dayLabel7 = new javax.swing.JLabel();
        startField7 = new javax.swing.JTextField();
        stopField7 = new javax.swing.JTextField();
        closedBox7 = new javax.swing.JCheckBox();
        nonStopBox7 = new javax.swing.JCheckBox();

        scheduleLabel.setText("Schedule:");

        headerLabels.setOpaque(false);

        dayHeader.setText("Day:");

        startHeader.setText("Starts:");

        startHeader1.setText("Ends:");

        closedHeader.setText("Closed");

        openHeader.setText("24/7");

        javax.swing.GroupLayout headerLabelsLayout = new javax.swing.GroupLayout(headerLabels);
        headerLabels.setLayout(headerLabelsLayout);
        headerLabelsLayout.setHorizontalGroup(
            headerLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLabelsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dayHeader)
                .addGap(59, 59, 59)
                .addComponent(startHeader)
                .addGap(23, 23, 23)
                .addComponent(startHeader1)
                .addGap(20, 20, 20)
                .addComponent(closedHeader)
                .addGap(13, 13, 13)
                .addComponent(openHeader))
        );
        headerLabelsLayout.setVerticalGroup(
            headerLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLabelsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dayHeader)
                    .addComponent(startHeader)
                    .addComponent(startHeader1)
                    .addComponent(closedHeader)
                    .addComponent(openHeader))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        content.setName("scheduleContent"); // NOI18N
        content.setOpaque(false);

        day1.setName("TheDay1"); // NOI18N
        day1.setOpaque(false);

        dayLabel1.setText("Monday");

        startField1.setText("12:00");
        startField1.setName(""); // NOI18N

        stopField1.setText("20:00");

        javax.swing.GroupLayout day1Layout = new javax.swing.GroupLayout(day1);
        day1.setLayout(day1Layout);
        day1Layout.setHorizontalGroup(
            day1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(day1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dayLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(startField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(stopField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(closedBox1)
                .addGap(18, 18, 18)
                .addComponent(nonStopBox1)
                .addContainerGap())
        );
        day1Layout.setVerticalGroup(
            day1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(day1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(day1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nonStopBox1)
                    .addComponent(closedBox1)
                    .addGroup(day1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dayLabel1)
                        .addComponent(startField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(stopField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        day2.setOpaque(false);

        dayLabel2.setText("Tuesday");

        startField2.setText("12:00");
        startField2.setName(""); // NOI18N
        startField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startField2ActionPerformed(evt);
            }
        });

        stopField2.setText("20:00");

        javax.swing.GroupLayout day2Layout = new javax.swing.GroupLayout(day2);
        day2.setLayout(day2Layout);
        day2Layout.setHorizontalGroup(
            day2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(day2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dayLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(startField2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(stopField2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(closedBox2)
                .addGap(18, 18, 18)
                .addComponent(nonStopBox2)
                .addContainerGap())
        );
        day2Layout.setVerticalGroup(
            day2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(day2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(day2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nonStopBox2)
                    .addComponent(closedBox2)
                    .addGroup(day2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dayLabel2)
                        .addComponent(startField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(stopField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        day3.setOpaque(false);

        dayLabel3.setText("Wednesday");

        startField3.setText("12:00");
        startField3.setName(""); // NOI18N

        stopField3.setText("20:00");

        javax.swing.GroupLayout day3Layout = new javax.swing.GroupLayout(day3);
        day3.setLayout(day3Layout);
        day3Layout.setHorizontalGroup(
            day3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(day3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dayLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(startField3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(stopField3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(closedBox3)
                .addGap(18, 18, 18)
                .addComponent(nonStopBox3)
                .addContainerGap())
        );
        day3Layout.setVerticalGroup(
            day3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(day3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(day3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nonStopBox3)
                    .addComponent(closedBox3)
                    .addGroup(day3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dayLabel3)
                        .addComponent(startField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(stopField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        day4.setOpaque(false);

        dayLabel4.setText("Thursday");

        startField4.setText("12:00");
        startField4.setName(""); // NOI18N

        stopField4.setText("20:00");

        javax.swing.GroupLayout day4Layout = new javax.swing.GroupLayout(day4);
        day4.setLayout(day4Layout);
        day4Layout.setHorizontalGroup(
            day4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(day4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dayLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(startField4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(stopField4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(closedBox4)
                .addGap(18, 18, 18)
                .addComponent(nonStopBox4)
                .addContainerGap())
        );
        day4Layout.setVerticalGroup(
            day4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(day4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(day4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nonStopBox4)
                    .addComponent(closedBox4)
                    .addGroup(day4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dayLabel4)
                        .addComponent(startField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(stopField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        day5.setOpaque(false);

        dayLabel5.setText("Friday");

        startField5.setText("12:00");
        startField5.setName(""); // NOI18N

        stopField5.setText("20:00");

        javax.swing.GroupLayout day5Layout = new javax.swing.GroupLayout(day5);
        day5.setLayout(day5Layout);
        day5Layout.setHorizontalGroup(
            day5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(day5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dayLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(startField5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(stopField5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(closedBox5)
                .addGap(18, 18, 18)
                .addComponent(nonStopBox5)
                .addContainerGap())
        );
        day5Layout.setVerticalGroup(
            day5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(day5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(day5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nonStopBox5)
                    .addComponent(closedBox5)
                    .addGroup(day5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dayLabel5)
                        .addComponent(startField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(stopField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        day6.setOpaque(false);

        dayLabel6.setText("Saturday");

        startField6.setText("12:00");
        startField6.setName(""); // NOI18N

        stopField6.setText("20:00");

        javax.swing.GroupLayout day6Layout = new javax.swing.GroupLayout(day6);
        day6.setLayout(day6Layout);
        day6Layout.setHorizontalGroup(
            day6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(day6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dayLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(startField6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(stopField6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(closedBox6)
                .addGap(18, 18, 18)
                .addComponent(nonStopBox6)
                .addContainerGap())
        );
        day6Layout.setVerticalGroup(
            day6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(day6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(day6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nonStopBox6)
                    .addComponent(closedBox6)
                    .addGroup(day6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dayLabel6)
                        .addComponent(startField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(stopField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        day7.setOpaque(false);

        dayLabel7.setText("Sunday");

        startField7.setText("12:00");
        startField7.setName(""); // NOI18N

        stopField7.setText("20:00");

        javax.swing.GroupLayout day7Layout = new javax.swing.GroupLayout(day7);
        day7.setLayout(day7Layout);
        day7Layout.setHorizontalGroup(
            day7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(day7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dayLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(startField7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(stopField7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(closedBox7)
                .addGap(18, 18, 18)
                .addComponent(nonStopBox7)
                .addContainerGap())
        );
        day7Layout.setVerticalGroup(
            day7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(day7Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(day7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nonStopBox7)
                    .addComponent(closedBox7)
                    .addGroup(day7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dayLabel7)
                        .addComponent(startField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(stopField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(day1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(day1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(day2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(day3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(day4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(day5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(day6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(day7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scheduleLabel)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerLabels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scheduleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(headerLabels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void startField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startField2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox closedBox1;
    private javax.swing.JCheckBox closedBox2;
    private javax.swing.JCheckBox closedBox3;
    private javax.swing.JCheckBox closedBox4;
    private javax.swing.JCheckBox closedBox5;
    private javax.swing.JCheckBox closedBox6;
    private javax.swing.JCheckBox closedBox7;
    private javax.swing.JLabel closedHeader;
    private javax.swing.JPanel content;
    private javax.swing.JPanel day1;
    private javax.swing.JPanel day2;
    private javax.swing.JPanel day3;
    private javax.swing.JPanel day4;
    private javax.swing.JPanel day5;
    private javax.swing.JPanel day6;
    private javax.swing.JPanel day7;
    private javax.swing.JLabel dayHeader;
    private javax.swing.JLabel dayLabel1;
    private javax.swing.JLabel dayLabel2;
    private javax.swing.JLabel dayLabel3;
    private javax.swing.JLabel dayLabel4;
    private javax.swing.JLabel dayLabel5;
    private javax.swing.JLabel dayLabel6;
    private javax.swing.JLabel dayLabel7;
    private javax.swing.JPanel headerLabels;
    private javax.swing.JCheckBox nonStopBox1;
    private javax.swing.JCheckBox nonStopBox2;
    private javax.swing.JCheckBox nonStopBox3;
    private javax.swing.JCheckBox nonStopBox4;
    private javax.swing.JCheckBox nonStopBox5;
    private javax.swing.JCheckBox nonStopBox6;
    private javax.swing.JCheckBox nonStopBox7;
    private javax.swing.JLabel openHeader;
    private javax.swing.JLabel scheduleLabel;
    private javax.swing.JTextField startField1;
    private javax.swing.JTextField startField2;
    private javax.swing.JTextField startField3;
    private javax.swing.JTextField startField4;
    private javax.swing.JTextField startField5;
    private javax.swing.JTextField startField6;
    private javax.swing.JTextField startField7;
    private javax.swing.JLabel startHeader;
    private javax.swing.JLabel startHeader1;
    private javax.swing.JTextField stopField1;
    private javax.swing.JTextField stopField2;
    private javax.swing.JTextField stopField3;
    private javax.swing.JTextField stopField4;
    private javax.swing.JTextField stopField5;
    private javax.swing.JTextField stopField6;
    private javax.swing.JTextField stopField7;
    // End of variables declaration//GEN-END:variables
}
