/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.group8.view.editRestaurant;

import com.group8.controller.RestaurantEditController;
import javax.swing.JComboBox;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author john
 */
public class RestaurantDetails extends javax.swing.JPanel {

    public JTextField getMaxPriceTextField() {
        return maxPriceTextField;
    }

    public void setMaxPriceTextField(JTextField maxPriceTextField) {
        this.maxPriceTextField = maxPriceTextField;
    }

    public JTextField getMinPriceTextField() {
        return minPriceTextField;
    }

    public void setMinPriceTextField(JTextField minPriceTextField) {
        this.minPriceTextField = minPriceTextField;
    }

    private RestaurantEditController controller;
    
    public JTextField getOwnerIDTextField(){
        return ownerIDTextField;
    }
    
    public void setOwnerIDTextField(JTextField ownerIDTextField){
        this.ownerIDTextField = ownerIDTextField;
    }
    
    public JTextField getAreaTextField() {
        return areaTextField;
    }

    public void setAreaTextField(JTextField areaTextField) {
        this.areaTextField = areaTextField;
    }

    public JTextField getCityTextField() {
        return cityTextField;
    }

    public void setCityTextField(JTextField cityTextField) {
        this.cityTextField = cityTextField;
    }

    public JTextField getImageURLTextField() {
        return imageURLTextField;
    }

    public void setImageURLTextField(JTextField imageURLTextField) {
        this.imageURLTextField = imageURLTextField;
    }

    public JTextField getTelephoneTextField() {
        return this.telephoneTextField;
    }
    
    public void setTelephoneTextField(JTextField telephoneTextField) {
        this.telephoneTextField = telephoneTextField;
    }

    public JComboBox getTypeComboBox() {
        return typeComboBox;
    }

    public void setTypeComboBox(JComboBox typeComboBox) {
        this.typeComboBox = typeComboBox;
    }

    public JTextArea getDescriptionTextArea() {
        return descriptionTextArea;
    }

    public void setDescriptionTextArea(JTextArea descriptionTextArea) {
        this.descriptionTextArea = descriptionTextArea;
    }

    public JTextField getNameTextField() {
        return nameTextField;
    }

    public void setNameTextField(JTextField nameTextField) {
        this.nameTextField = nameTextField;
    }

    public JTextField getStreetTextField() {
        return streetTextField;
    }

    public void setStreetTextField(JTextField streetTextField) {
        this.streetTextField = streetTextField;
    }

    public JTextField getZipCodeTextField() {
        return zipCodeTextField;
    }

    public void setZipCodeTextField(JTextField zipCodeTextField) {
        this.zipCodeTextField = zipCodeTextField;
    }

    /**
     * Creates new form RestaurantDetails
     */
    public RestaurantDetails(RestaurantEditController controller) {
        this.controller = controller;
        initComponents();
    }
    
    public RestaurantDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        detailsLabel = new javax.swing.JLabel();
        ownerIDLabel = new javax.swing.JLabel();
        ownerIDTextField = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        streetLabel = new javax.swing.JLabel();
        areaLabel = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        zipCodeLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        streetTextField = new javax.swing.JTextField();
        areaTextField = new javax.swing.JTextField();
        cityTextField = new javax.swing.JTextField();
        zipCodeTextField = new javax.swing.JTextField();
        telephoneTextField = new javax.swing.JTextField();
        imageURLTextField = new javax.swing.JTextField();
        typeComboBox = new javax.swing.JComboBox();
        imageURLLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        telephoneLabel = new javax.swing.JLabel();
        priceRangeLabel = new javax.swing.JLabel();
        maxPriceTextField = new javax.swing.JTextField();
        minPriceTextField = new javax.swing.JTextField();
        typeLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(320, 470));
        setMinimumSize(new java.awt.Dimension(320, 470));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(320, 470));
        setSize(new java.awt.Dimension(320, 470));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        detailsLabel.setText("Restaurant Details:");
        add(detailsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        ownerIDLabel.setText("OwnerID:");
        ownerIDLabel.setMaximumSize(new java.awt.Dimension(80, 15));
        ownerIDLabel.setMinimumSize(new java.awt.Dimension(80, 15));
        ownerIDLabel.setPreferredSize(new java.awt.Dimension(80, 30));
        add(ownerIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        ownerIDTextField.setMaximumSize(new java.awt.Dimension(205, 30));
        ownerIDTextField.setMinimumSize(new java.awt.Dimension(205, 30));
        ownerIDTextField.setName("ownerID"); // NOI18N
        ownerIDTextField.setPreferredSize(new java.awt.Dimension(205, 30));
        add(ownerIDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 20, 205, -1));

        nameLabel.setText("Name:");
        nameLabel.setMaximumSize(new java.awt.Dimension(80, 15));
        nameLabel.setMinimumSize(new java.awt.Dimension(80, 15));
        nameLabel.setPreferredSize(new java.awt.Dimension(80, 30));
        add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 55, -1, -1));

        typeLabel.setText("Type:");
        typeLabel.setMaximumSize(new java.awt.Dimension(80, 15));
        typeLabel.setMinimumSize(new java.awt.Dimension(80, 15));
        typeLabel.setPreferredSize(new java.awt.Dimension(80, 30));
        add(typeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        streetLabel.setText("Street:");
        streetLabel.setMaximumSize(new java.awt.Dimension(80, 15));
        streetLabel.setMinimumSize(new java.awt.Dimension(80, 15));
        streetLabel.setPreferredSize(new java.awt.Dimension(80, 30));
        add(streetLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 125, -1, -1));

        areaLabel.setText("Area:");
        areaLabel.setMaximumSize(new java.awt.Dimension(80, 15));
        areaLabel.setMinimumSize(new java.awt.Dimension(80, 15));
        areaLabel.setPreferredSize(new java.awt.Dimension(80, 30));
        add(areaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        cityLabel.setText("City:");
        cityLabel.setMaximumSize(new java.awt.Dimension(80, 15));
        cityLabel.setMinimumSize(new java.awt.Dimension(80, 15));
        cityLabel.setPreferredSize(new java.awt.Dimension(80, 30));
        add(cityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 195, -1, -1));

        zipCodeLabel.setText("Zip Code:");
        zipCodeLabel.setMaximumSize(new java.awt.Dimension(80, 15));
        zipCodeLabel.setMinimumSize(new java.awt.Dimension(80, 15));
        zipCodeLabel.setPreferredSize(new java.awt.Dimension(80, 30));
        add(zipCodeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        nameTextField.setMaximumSize(new java.awt.Dimension(205, 30));
        nameTextField.setMinimumSize(new java.awt.Dimension(205, 30));
        nameTextField.setName("name"); // NOI18N
        nameTextField.setPreferredSize(new java.awt.Dimension(205, 30));
        add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 55, 205, -1));

        streetTextField.setMaximumSize(new java.awt.Dimension(205, 30));
        streetTextField.setMinimumSize(new java.awt.Dimension(205, 30));
        streetTextField.setName("street"); // NOI18N
        streetTextField.setPreferredSize(new java.awt.Dimension(205, 30));
        add(streetTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 125, 205, -1));

        areaTextField.setMaximumSize(new java.awt.Dimension(205, 30));
        areaTextField.setMinimumSize(new java.awt.Dimension(205, 30));
        areaTextField.setName("area"); // NOI18N
        areaTextField.setPreferredSize(new java.awt.Dimension(205, 30));
        add(areaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 160, 205, -1));

        cityTextField.setMaximumSize(new java.awt.Dimension(205, 30));
        cityTextField.setMinimumSize(new java.awt.Dimension(205, 30));
        cityTextField.setName("city"); // NOI18N
        cityTextField.setPreferredSize(new java.awt.Dimension(205, 30));
        add(cityTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 195, 205, -1));

        zipCodeTextField.setMaximumSize(new java.awt.Dimension(205, 30));
        zipCodeTextField.setMinimumSize(new java.awt.Dimension(205, 30));
        zipCodeTextField.setName("zipCode"); // NOI18N
        zipCodeTextField.setPreferredSize(new java.awt.Dimension(205, 30));
        add(zipCodeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 230, 205, -1));

        telephoneTextField.setMaximumSize(new java.awt.Dimension(205, 30));
        telephoneTextField.setMinimumSize(new java.awt.Dimension(205, 30));
        telephoneTextField.setName("telephone"); // NOI18N
        telephoneTextField.setPreferredSize(new java.awt.Dimension(205, 30));
        add(telephoneTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 300, 205, -1));

        imageURLTextField.setMaximumSize(new java.awt.Dimension(205, 30));
        imageURLTextField.setMinimumSize(new java.awt.Dimension(205, 30));
        imageURLTextField.setName("imageURL"); // NOI18N
        imageURLTextField.setPreferredSize(new java.awt.Dimension(205, 30));
        add(imageURLTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 265, 205, -1));

        typeComboBox.setMaximumSize(new java.awt.Dimension(205, 30));
        typeComboBox.setMinimumSize(new java.awt.Dimension(205, 30));
        typeComboBox.setName("type"); // NOI18N
        typeComboBox.setPreferredSize(new java.awt.Dimension(205, 30));
        add(typeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 90, 205, -1));

        imageURLLabel.setText("Image URL:");
        imageURLLabel.setMaximumSize(new java.awt.Dimension(80, 15));
        imageURLLabel.setMinimumSize(new java.awt.Dimension(80, 15));
        imageURLLabel.setPreferredSize(new java.awt.Dimension(80, 30));
        add(imageURLLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 265, -1, -1));

        descriptionLabel.setText("Description:");
        descriptionLabel.setMaximumSize(new java.awt.Dimension(80, 15));
        descriptionLabel.setMinimumSize(new java.awt.Dimension(80, 15));
        descriptionLabel.setPreferredSize(new java.awt.Dimension(80, 30));
        add(descriptionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        jScrollPane1.setMaximumSize(new java.awt.Dimension(200, 84));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(200, 84));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(200, 84));
        jScrollPane1.setSize(new java.awt.Dimension(200, 84));

        descriptionTextArea.setColumns(20);
        descriptionTextArea.setLineWrap(true);
        descriptionTextArea.setRows(5);
        descriptionTextArea.setWrapStyleWord(true);
        descriptionTextArea.setLocation(new java.awt.Point(105, 335));
        descriptionTextArea.setMaximumSize(new java.awt.Dimension(15, 80));
        descriptionTextArea.setMinimumSize(new java.awt.Dimension(15, 80));
        descriptionTextArea.setName("description"); // NOI18N
        descriptionTextArea.setPreferredSize(new java.awt.Dimension(15, 80));
        descriptionTextArea.setSize(new java.awt.Dimension(15, 80));
        jScrollPane1.setViewportView(descriptionTextArea);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 338, -1, -1));

        telephoneLabel.setText("Telephone:");
        telephoneLabel.setMaximumSize(new java.awt.Dimension(80, 15));
        telephoneLabel.setMinimumSize(new java.awt.Dimension(80, 15));
        telephoneLabel.setPreferredSize(new java.awt.Dimension(80, 30));
        add(telephoneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        priceRangeLabel.setText("Price range:");
        priceRangeLabel.setMaximumSize(new java.awt.Dimension(80, 15));
        priceRangeLabel.setMinimumSize(new java.awt.Dimension(80, 15));
        priceRangeLabel.setPreferredSize(new java.awt.Dimension(80, 30));
        add(priceRangeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 428, -1, -1));

        maxPriceTextField.setMaximumSize(new java.awt.Dimension(95, 30));
        maxPriceTextField.setMinimumSize(new java.awt.Dimension(95, 30));
        maxPriceTextField.setName("maxPrice"); // NOI18N
        maxPriceTextField.setPreferredSize(new java.awt.Dimension(95, 30));
        maxPriceTextField.setSize(new java.awt.Dimension(95, 30));
        add(maxPriceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 428, -1, 30));

        minPriceTextField.setMaximumSize(new java.awt.Dimension(95, 30));
        minPriceTextField.setMinimumSize(new java.awt.Dimension(95, 30));
        minPriceTextField.setName("minPrice"); // NOI18N
        minPriceTextField.setPreferredSize(new java.awt.Dimension(95, 30));
        add(minPriceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 428, -1, 30));

        typeLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        typeLabel2.setText("-");
        typeLabel2.setMaximumSize(new java.awt.Dimension(5, 30));
        typeLabel2.setMinimumSize(new java.awt.Dimension(5, 30));
        typeLabel2.setPreferredSize(new java.awt.Dimension(5, 30));
        typeLabel2.setSize(new java.awt.Dimension(5, 30));
        add(typeLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 428, 5, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel areaLabel;
    private javax.swing.JTextField areaTextField;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JLabel detailsLabel;
    private javax.swing.JLabel imageURLLabel;
    private javax.swing.JTextField imageURLTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField maxPriceTextField;
    private javax.swing.JTextField minPriceTextField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel ownerIDLabel;
    private javax.swing.JTextField ownerIDTextField;
    private javax.swing.JLabel priceRangeLabel;
    private javax.swing.JLabel streetLabel;
    private javax.swing.JTextField streetTextField;
    private javax.swing.JLabel telephoneLabel;
    private javax.swing.JTextField telephoneTextField;
    private javax.swing.JComboBox typeComboBox;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JLabel typeLabel2;
    private javax.swing.JLabel zipCodeLabel;
    private javax.swing.JTextField zipCodeTextField;
    // End of variables declaration//GEN-END:variables

}